# KEYWORDS.....
# python has a set of keywords that are reserved words that cannot be used as variable names, function names or any other identifiers.

# and          ("A logiacal operator")
# as           ("To create an alias")
# assert       ("For debugging")
# break        ("to break out of a loop")
# class        ("to define a class")
# continue     ("To continue to the next iteration of a loop ")
# def          ("to define a function")
# del          ("to delete an object")
# elif         ("used in conditional statements, same as else if")
# else         ("used in conditional statements")
# except       ("used with exceptions, a block of code that will be executed no matter if there is an exception or not")
# False        ("boolean value, result of comparison operations")
# finally      ("used with exceptions, a block of code that will be executed no matter if there is an exception or not")
# for          ("to create a for loop")
# from         ("to import specific parts of a module")
# global       ("to declare a global variable")
# if           ("to make a conditional satatement")
# import       ("to import a module")
# in           ("to check if a value is present in a list ,tuple ,etc")
# is           ("to test if two variables are equal")
# lambda       ("to create an anonymous function")
# None         ("represents a null value")
# nonlocal     ("to declare a non-local variable")
# not          ("a logical operator")
# or           ("a logical operator")
# pass         ("a null statement, a statement that will do nothing")
# raise        ("to raise an exception")
# return       ("to exit a function and return a value")
# True         ("boolean value, result of comparison operations")
# try          ("to make a try... except statement")
# while        ("to crate a while loop")
# with         ("used to simplify exception handling")
# yield        ("to return a list of values from a generator")